Mail.Client/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MailClient.Models;

namespace MailClient.Controllers
{
    [Authorize]
    public class MailController : Controller
    {
        //
        // GET: /Mail/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Mail/SentMail

        public ActionResult SentMail()
        {
            return View();
        }

        //
        // GET: /Mail/Details?mailBox=Inbox&id=6

        public ActionResult Details(string mailBox, int id)
        {
            var mailModel = new MailModel
            {
                MailId = id,
                MailBox = mailBox
            };

            return View(mailModel);
        }

        //
        // GET: /Mail/Compose

        public ActionResult Compose()
        {
            return View();
        }

        //
        // POST: /Mail/Compose

        [HttpPost]
        public ActionResult Compose(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Mail.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css")
        @Styles.Render("~/Content/css")

        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        
        <script type="text/javascript" src="~/Scripts/MailClient/HelperFunctions.js"></script>

        @RenderSection("scripts", required: false)
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Nikhil Garg Mail Client", "Index", "Mail")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Inbox", "Index", "Mail")</li>
                            <li>@Html.ActionLink("Sent Mail", "SentMail", "Mail")</li>
                            <li>@Html.ActionLink("Compose", "Compose", "Mail")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @Html.HiddenFor(u => User.Identity.Name)

            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                <img src="~/Content/themes/images/ajax-loader.gif" width="100" height="100" alt="Loading..."
                     style="display:none" id="loadingImage"/>
                
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Nikhil Garg Mail Client</p>
                </div>
            </div>
        </footer>
    </body>
</html>